{% set name = "RIFT" %}
{% set version = "0.0.15.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0708ceda136281e9e0c05d13281b9f0ee497d064c4b3b72ba365b5518d93b9c9

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    # for cross-compiling:
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - python                              # [build_platform != target_platform]
  host:
    - pip
    - python
    - setuptools
  run:
    - corner
    - gwdatafind
    - h5py
    - lalsuite
    - ligo-segments
    - ligo.skymap
    - matplotlib-base
    - numba
    - numpy
    - pip
    - precession
    - python
    - python-ligo-lw
    - scikit-learn
    - setuptools

test:
  requires:
    - pip
  imports:
    - RIFT
    - RIFT.integrators
    - RIFT.interpolators
    - RIFT.likelihood
    - RIFT.physics
  commands:
    # check requirements
    - python -m pip check RIFT
    - python -m pip show RIFT
    # set environment
    - export EOB_ARCHIVE="${HOME}"
    - export EOB_BASE=""
    - export EOB_C_BASE=""
    - export EOB_C_ARCHIVE="${HOME}"
    - export EOB_C_ARCHIVE_NMAX="1"
    - export EOS_TABLES="${HOME}"
    - export GW_SURROGATE=""
    - export MATLAB_BASE=""
    - export MPLBACKEND="agg"
    # test scripts
    - convergence_test_samples.py --help
    - convert_dat_to_hdf5.py --help
    - convert_output_format_ile2inference --help
    - convert_output_format_inference2ile --help
    - convert_psd_ascii2xml --help
    - create_event_parameter_pipeline_BasicIteration --help
    - create_postprocessing_event_dag.py --help
    - helper_LDG_Events.py --help
    - integrate_likelihood_extrinsic --help
    - integrate_likelihood_extrinsic_batchmode --help
    - integrate_likelihood_extrinsic_no-op --help
    - plot_posterior_corner.py --help
    - util_AdaptiveExponent.py --help
    - util_CoincIFOUtility.py --help
    - util_ConstructIntrinsicPosterior_GenericCoordinates.py --help
    - util_EstimateWaveformDuration.py --help
    - util_FrameZeroNoiseSNR.py --help
    - util_GenerateMaxlnLWaveform.py --help
    - util_GridRecenter.py --help
    - util_ILENextGeneration.py --help
    - util_IterativeFisher.py --help
    - util_JoinXML.py --help
    - util_LALCompareApproximantsOnSamples.py --help
    - util_LALWriteFrame.py --help
    - util_ManualOverlapGrid.py --help
    - util_MarginalizedLikelihoodEOSIntegralFromIntermediate.py --help
    - util_MassGrid.py --help
    - util_MassGridCoalesce.py --help
    - util_ParameterFilter.py --help
    - util_ParameterPuffball.py --help
    - util_ParameterRandomize.py --help
    - util_PrintInjection.py --help
    - util_ROMWriteFrame.py --help
    - util_ResampleILEOutputWithExtrinsic.py --help
    - util_TestSpokesIO.py --help
    - util_TestXMLParameterStorage.py --help
    - util_TidalPlotSimulationStrain.py --help
    - util_WriteInjectionFile.py --help

outputs:
  - name: rift

  - name: rift-gpu
    build:
      skip: true  # [not linux]
    requirements:
      host:
        - python
      run:
        - cupy
        - python
        - pytorch
        - {{ pin_subpackage('rift', exact=True) }}
    # NOTE: we can't run the tests because we don't have access to a GPU
    #       everywhere
    #test:
    #  imports:
    #    - RIFT.likelihood.optimized_gpu_tools
    about:
      home: https://git.ligo.org/richard-oshaughnessy/research-projects-RIT
      dev_url: https://git.ligo.org/richard-oshaughnessy/research-projects-RIT
      license: MIT
      license_family: MIT
      license_file: LICENSE.md
      summary: RIFT parameter estimation pipeline GPU metapackage

about:
  home: https://git.ligo.org/richard-oshaughnessy/research-projects-RIT
  dev_url: https://git.ligo.org/richard-oshaughnessy/research-projects-RIT
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: RIFT parameter estimation pipeline

extra:
  recipe-maintainers:
    - duncanmmacleod
    - oshaughn
